function _G.self_color_solarized_dark()
  vim.g.solarized_italics = 1

  vim.cmd('set background=dark')
  vim.cmd('colorscheme solarized')

  vim.cmd('highlight StatusLine                                                                                guifg=#073642')

  vim.cmd('highlight GalaxyLeftGitDiffAddActive                                                                guibg=#073642 guifg=#00aa00')
  vim.cmd('highlight GalaxyLeftGitDiffInactive                                                                 guibg=#073642 guifg=#93a1a1')
  vim.cmd('highlight GalaxyLeftGitDiffModifiedActive                                                           guibg=#073642 guifg=#ffa003')
  vim.cmd('highlight GalaxyLeftGitDiffRemoveActive                                                             guibg=#073642 guifg=#dc322f')
  vim.cmd('highlight GalaxyLeftLspInactive                                                                     guibg=#073642 guifg=#93a1a1')
  vim.cmd('highlight GalaxyMapperCommon1                                                                       guibg=#073642 guifg=#657b83')
  vim.cmd('highlight GalaxyMapperCommon2                                                                       guibg=#93a1a1 guifg=#002b36')
  vim.cmd('highlight GalaxyMapperCommon3                                                                       guibg=#073642 guifg=#93a1a1')
  vim.cmd('highlight GalaxyMapperCommon4                                                                       guibg=#657b83 guifg=#002b36')
  vim.cmd('highlight GalaxyMapperCommon5                                                                       guibg=#073642 guifg=#93a1a1')
  vim.cmd('highlight GalaxyMapperCommon6                                                                       guibg=#657b83 guifg=#002b36')
  vim.cmd('highlight GalaxyMapperCommon7                                                                       guibg=#657b83 guifg=#93a1a1')
  vim.cmd('highlight GalaxyMapperCommon8                                                                       guibg=#657b83 guifg=#91a6ba')
  vim.cmd('highlight GalaxyMidFileStatusModified                                                               guibg=#073642 guifg=#00aa00')
  vim.cmd('highlight GalaxyMidFileStatusReadonly                                                               guibg=#073642 guifg=#ffa003')
  vim.cmd('highlight GalaxyMidFileStatusRestricted                                                             guibg=#073642 guifg=#dc322f')
  vim.cmd('highlight GalaxyMidFileStatusUnmodified                                                             guibg=#073642 guifg=#93a1a1')
  vim.cmd('highlight GalaxyRightLspErrorActive                                                                 guibg=#073642 guifg=#dc322f')
  vim.cmd('highlight GalaxyRightLspHintActive                                                                  guibg=#073642 guifg=#00aa00')
  vim.cmd('highlight GalaxyRightLspInformationActive                                                           guibg=#073642 guifg=#258bd2')
  vim.cmd('highlight GalaxyRightLspWarningActive                                                               guibg=#073642 guifg=#ffa003')
  vim.cmd('highlight GalaxyViModeCommandInverted                                                               guibg=#657b83 guifg=#258bd2')
  vim.cmd('highlight GalaxyViModeCommandUnturned                                                               guibg=#258bd2 guifg=#002b36')
  vim.cmd('highlight GalaxyViModeCommonVisualInverted                                                          guibg=#657b83 guifg=#d43681')
  vim.cmd('highlight GalaxyViModeCommonVisualUnturned                                                          guibg=#d43681 guifg=#002b36')
  vim.cmd('highlight GalaxyViModeEmptyInverted                                                                 guibg=#657b83 guifg=#93a1a1')
  vim.cmd('highlight GalaxyViModeEmptyUnturned                                                                 guibg=#93a1a1 guifg=#002b36')
  vim.cmd('hihlight GalaxyViModeInsertInverted                                                                guibg=#657b83 guifg=#859a00')
  vim.cmd('highlight GalaxyViModeInsertUnturned                                                                guibg=#859a00 guifg=#002b36')
  vim.cmd('highlight GalaxyViModeNormalInverted                                                                guibg=#657b83 guifg=#93a1a1')
  vim.cmd('highlight GalaxyViModeNormalUnturned                                                                guibg=#93a1a1 guifg=#002b36')
  vim.cmd('highlight GalaxyViModeReplaceInverted                                                               guibg=#657b83 guifg=#dc322f')
  vim.cmd('highlight GalaxyViModeReplaceUnturned                                                               guibg=#dc322f guifg=#002b36')
  vim.cmd('highlight GalaxyViModeShellInverted                                                                 guibg=#657b83 guifg=#2aa198')
  vim.cmd('highlight GalaxyViModeShellUnturned                                                                 guibg=#2aa198 guifg=#002b36')
  vim.cmd('highlight GalaxyViModeTerminalInverted                                                              guibg=#657b83 guifg=#2aa198')
  vim.cmd('highlight GalaxyViModeTerminalUnturned                                                              guibg=#2aa198 guifg=#002b36')
end

function _G.self_color_solarized_light()
  vim.g.solarized_italics = 1

  vim.cmd('set background=light')
  vim.cmd('colorscheme solarized')

  vim.cmd('highlight StatusLine                                                                                              guifg=#eee8d5')

  vim.cmd('highlight GalaxyLeftGitDiffAddActive                                                                guibg=#eee8d5 guifg=#28a228')
  vim.cmd('highlight GalaxyLeftGitDiffInactive                                                                 guibg=#eee8d5 guifg=#586e75')
  vim.cmd('highlight GalaxyLeftGitDiffModifiedActive                                                           guibg=#eee8d5 guifg=#b8860b')
  vim.cmd('highlight GalaxyLeftGitDiffRemoveActive                                                             guibg=#eee8d5 guifg=#dc143c')
  vim.cmd('highlight GalaxyLeftLspInactive                                                                     guibg=#eee8d5 guifg=#586e75')
  vim.cmd('highlight GalaxyMapperCommon1                                                                       guibg=#eee8d5 guifg=#ded8c7')
  vim.cmd('highlight GalaxyMapperCommon2                                                                       guibg=#cac4b5 guifg=#586e75')
  vim.cmd('highlight GalaxyMapperCommon3                                                                       guibg=#eee8d5 guifg=#93a1a1')
  vim.cmd('highlight GalaxyMapperCommon4                                                                       guibg=#ded8c7 guifg=#586e75')
  vim.cmd('highlight GalaxyMapperCommon5                                                                       guibg=#eee8d5 guifg=#586e75')
  vim.cmd('highlight GalaxyMapperCommon6                                                                       guibg=#ded8c7 guifg=#586e75')
  vim.cmd('highlight GalaxyMapperCommon7                                                                       guibg=#ded8c7 guifg=#cac4b5')
  vim.cmd('highlight GalaxyMapperCommon8                                                                       guibg=#ded8c7 guifg=#fefefe')
  vim.cmd('highlight GalaxyMidFileStatusModified                                                               guibg=#eee8d5 guifg=#28a228')
  vim.cmd('highlight GalaxyMidFileStatusReadonly                                                               guibg=#eee8d5 guifg=#b8860b')
  vim.cmd('highlight GalaxyMidFileStatusRestricted                                                             guibg=#eee8d5 guifg=#dc143c')
  vim.cmd('highlight GalaxyMidFileStatusUnmodified                                                             guibg=#eee8d5 guifg=#586e75')
  vim.cmd('highlight GalaxyRightLspErrorActive                                                                 guibg=#eee8d5 guifg=#dc143c')
  vim.cmd('highlight GalaxyRightLspHintActive                                                                  guibg=#eee8d5 guifg=#28a228')
  vim.cmd('highlight GalaxyRightLspInformationActive                                                           guibg=#eee8d5 guifg=#258bd2')
  vim.cmd('highlight GalaxyRightLspWarningActive                                                               guibg=#eee8d5 guifg=#b8860b')
  vim.cmd('highlight GalaxyViModeCommandInverted                                                               guibg=#ded8c7 guifg=#258bd2')
  vim.cmd('highlight GalaxyViModeCommandUnturned                                                               guibg=#258bd2 guifg=#ded8c7')
  vim.cmd('highlight GalaxyViModeCommonVisualInverted                                                          guibg=#ded8c7 guifg=#d43681')
  vim.cmd('highlight GalaxyViModeCommonVisualUnturned                                                          guibg=#d43681 guifg=#ded8c7')
  vim.cmd('highlight GalaxyViModeEmptyInverted                                                                 guibg=#ded8c7 guifg=#cac4b5')
  vim.cmd('highlight GalaxyViModeEmptyUnturned                                                                 guibg=#cac4b5 guifg=#ded8c7')
  vim.cmd('highlight GalaxyViModeInsertInverted                                                                guibg=#ded8c7 guifg=#859a00')
  vim.cmd('highlight GalaxyViModeInsertUnturned                                                                guibg=#859a00 guifg=#ded8c7')
  vim.cmd('highlight GalaxyViModeNormalInverted                                                                guibg=#ded8c7 guifg=#cac4b5')
  vim.cmd('highlight GalaxyViModeNormalUnturned                                                                guibg=#cac4b5 guifg=#586e75')
  vim.cmd('highlight GalaxyViModeReplaceInverted                                                               guibg=#ded8c7 guifg=#dc143c')
  vim.cmd('highlight GalaxyViModeReplaceUnturned                                                               guibg=#dc143c guifg=#ded8c7')
  vim.cmd('highlight GalaxyViModeShellInverted                                                                 guibg=#ded8c7 guifg=#2aa198')
  vim.cmd('highlight GalaxyViModeShellUnturned                                                                 guibg=#2aa198 guifg=#ded8c7')
  vim.cmd('highlight GalaxyViModeTerminalInverted                                                              guibg=#ded8c7 guifg=#2aa198')
  vim.cmd('highlight GalaxyViModeTerminalUnturned                                                              guibg=#2aa198 guifg=#ded8c7')
end
