#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# ##############################################################################
# #                                AUTOSTART APPS                              #
# ##############################################################################
killall autostart.sh
$HOME/.config/bspwm/autostart.sh
picom --config $HOME/.config/picom/picom.conf &
sh $HOME/.config/polybar/launch.sh

#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

bspc monitor -d 1 2 3 4 5

## This creates and names desktops for multiple monitors.
xworkspaces_multimonitor &

# BSPWM configuration
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config single_monocle       false
bspc config borderless_monocle   false
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
#bspc config click_to_focus       true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config border_radius        8
bspc config border_width         2
bspc config window_gap           2
bspc config top_padding          37
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config split_ratio          0.50

# BSPWM coloring
bspc config normal_border_color  "#13141d"
bspc config active_border_color  "#13141d"
bspc config focused_border_color "#5e81ac"

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

# Specific Workspaces
bspc rule -a Spotify desktop=^5
bspc rule -a Thunderbird desktop=^4

# Floating applications
bspc rule -a Matlab state=floating
bspc rule -a nm-applet state=floating
bspc rule -a Arandr state=floating
bspc rule -a Pavucontrol state=floating sticky=on

# Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

# polybar hidden when fullscreen for vlc, youtube, mpv ...
# find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window

# rename WM to not have problems with java programs (e.g. matlab)
wmname LG3D

