#! /bin/sh

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
if [ -x "$HOME"/.bin/dualmonitor_setup_laptop ];then
    dualmonitor_setup_laptop
fi

# restart apps when reloading bspwm
killall autostart
"$HOME"/.config/bspwm/autostart.sh

pgrep -x sxhkd > /dev/null || sxhkd &
# ##############################################################################
# #                            GENERAL CONFIGURATION                           #
# ##############################################################################

## This creates and names desktops for multiple monitors.
# xworkspaces_multimonitor &

# BSPWM configuration
bspc config pointer_m qodifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config single_monocle       false
bspc config borderless_monocle   false
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
#bspc config click_to_focus       true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config border_radius        8
bspc config border_width         2
bspc config window_gap           2
bspc config top_padding          37
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config split_ratio          0.50

# BSPWM coloring
bspc config normal_border_color  "#13141d"
bspc config active_border_color  "#13141d"
bspc config focused_border_color "5e81ac"

# ##############################################################################
# #                                 WINDOW RULES                               #
# ##############################################################################

# Specific Workspaces
bspc rule -a Spotify desktop=^5
bspc rule -a Thunderbird desktop=^4
bspc rule -a Prospect Mail desktop=^4

# Floating applications
bspc rule -a nm-applet state=floating
bspc rule -a Arandr state=floating center=on follow=on rectangle=930x617+0+0
bspc rule -a Pavucontrol state=floating center=on follow=on rectangle=930x617+0+0

# Tiled applications
bspc rule -a zathura state=tiled

# rename WM to not have problems with java programs (e.g. matlab)
wmname LG3D
